- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/Prasanthreddy4a5/cart" }
    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/Prasanthreddy4a5/roboshop-terraform" }
